server:
  port: ${PORT:8090}
  forward-headers-strategy: framework
        
## Classic Eureka configuration
eureka:
  instance:
    preferIpAddress: false
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

## Configuration for App name, security using OAuth2 and gateway
spring:
  application:
    name: ${HOSTNAME:ms-gateway}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://vinovivo-production.up.railway.app/realms/vino-vivo/protocol/openid-connect/certs}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors: ## CORS Configuration
        cors-configurations:
          '[/**]': ## For all routes
            allowedOrigins: ${ALLOWED_ORIGINS:*} # With '*' we allow all origins. We can restrict by indicating domains or ip + port, e.g. http://localhost:3000 (where our front is, or a Vercel domain)
            allowedHeaders: "*" ## All headers allowed
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS

## Configuration for Springdoc
## This includes the paths for API docs and Swagger UI of each microservice
springdoc:
  api-docs:
    paths:
      ms-commerce: /ms-commerce/v3/api-docs
      ms-users: /ms-users/v3/api-docs
  swagger-ui:
    paths:
      ms-commerce: /ms-commerce/swagger-ui.html
      ms-users: /ms-users/swagger-ui.html
  enable: true

## We enable the Actuator API to be able to access <<host>>/actuator/gateway/routes
## We expose the routings that have been automatically detected (all)
## Depending on the ROUTE_TABLES_ENABLED environment variable (true by default)
management:
  endpoint:
    gateway:  
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
        - '*'