server:
  port: ${PORT:8888}

spring:
  application:
    name: msconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gaghyta/VinoVivo-back-ms-configserver

management:
  endpoints:
    web:
      exposure:
        include: "*"
