## Instance port
server:
  port: ${PORT:8081}

## Configuration for App name and Spring Data
spring:
  application:
    name: ${APP_NAME:ms-users}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://vinovivo-production.up.railway.app/realms/vino-vivo
          jwk-set-uri: https://vinovivo-production.up.railway.app/realms/vino-vivo/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: backend-client
            client-secret: ${CLIENT_SECRET:5UBesc2Jn2tl3sQPsxsnI8wHugQk3DC5}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            tokenUri: https://vinovivo-production.up.railway.app/realms/vino-vivo/protocol/openid-connect/token

proyecto:
  keycloak:
    serverUrl: https://vinovivo-production.up.railway.app
    clientId: backend-client
    clientSecret: ${CLIENT_SECRET:5UBesc2Jn2tl3sQPsxsnI8wHugQk3DC5}
    realm: vino-vivo

## Configuration for Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: false
    # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}
